/**
 * Design: portal independente de grupos, focado em cadastro, código de acesso e trabalho colaborativo.
 */
import { Link } from "wouter";
import { ArrowLeft, BrainCircuit, ChartNoAxesCombined, Loader2, UsersRound } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { GroupArea } from "./Home";

export default function GroupAccess() {
  const activity = trpc.collaboration.activity.useQuery(undefined, { staleTime: 15_000 });
  return <div className="min-h-screen bg-[#F6F1E8] text-[#183135]"><div className="app-grain pointer-events-none fixed inset-0 opacity-40" /><header className="relative z-10 border-b border-[#183135]/10 bg-[#F6F1E8]/90"><div className="mx-auto flex max-w-[1500px] items-center justify-between gap-4 px-4 py-4 sm:px-8"><div className="flex items-center gap-3"><div className="grid size-11 place-items-center rounded-2xl bg-[#0C4A5A] text-[#F7EACB]"><UsersRound className="size-6" /></div><div><p className="font-display text-lg font-semibold leading-none text-[#163C43]">Modelo Dinâmico</p><p className="mt-1 text-[10px] font-bold uppercase tracking-[.18em] text-[#658083]">Inteligência de mercado · MBA</p></div></div><div className="flex items-center gap-2"><Link href="/grupos/evolucao" className="inline-flex items-center gap-2 rounded-xl bg-[#0C4A5A] px-3 py-2 text-xs font-bold text-white transition hover:bg-[#163F47]"><ChartNoAxesCombined className="size-4" />Evolução da turma</Link><Link href="/" className="inline-flex items-center gap-2 rounded-xl border border-[#183135]/15 bg-[#FFFCF5] px-3 py-2 text-xs font-bold text-[#31595C] transition hover:bg-white"><ArrowLeft className="size-4" />Painel do professor</Link></div></div></header><main className="relative z-10 mx-auto max-w-[1500px] px-4 py-8 sm:px-8 sm:py-10"><section className="mb-7 overflow-hidden rounded-[1.75rem] bg-[#153F47] p-6 text-white sm:p-8"><div className="grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#F6D58A]">Ambiente dos estudantes</p><h1 className="mt-3 font-display text-4xl font-semibold leading-tight">Cadastre o grupo.</h1></div><p className="self-end text-sm leading-6 text-[#D5E5E1]">Registre os integrantes, guarde o código de acesso e construa evidências para cada meta. As respostas alimentam os indicadores de cobertura, triangulação de fontes, FCS, KIQs e recomendação.</p></div></section>{activity.isLoading ? <div className="research-card grid min-h-64 place-items-center"><Loader2 className="size-7 animate-spin text-[#0C4A5A]" /></div> : <GroupArea activity={activity.data} />}</main></div>;
}
